/*
 *
 * Map constants
 *
 */

export const MAP_MOUNTED_AND_RENDERED = 'app/Map/MAP_MOUNTED_AND_RENDERED';
export const GET_POKEMONS_IN_AREA_REQUEST = 'app/Map/GET_POKEMONS_IN_AREA_REQUEST';
export const GET_POKEMONS_IN_AREA_SUCCESS = 'app/Map/GET_POKEMONS_IN_AREA_SUCCESS';
export const GET_POKEMONS_IN_AREA_ERROR = 'app/Map/GET_POKEMONS_IN_AREA_ERROR';
